name:                vdiff
version:             0.1.0.0
synopsis:         A simple tool to compare static program verifiers
github:            https://github.com/chkl/vdiff
author:              Christian Klinger
maintainer:          io@klinch.de
copyright:           All Rights Reserved
license:             AllRightsReserved
category:            Misc
build-type:          Simple

extra-source-files:
  - README.md
  - assets/**


default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - LambdaCase
  - ScopedTypeVariables
  - DeriveFunctor
  - GeneralizedNewtypeDeriving
  - TypeFamilies
  - FlexibleContexts
  - FlexibleInstances
  - StandaloneDeriving


executables:
  vdiff:
    source-dirs: app/vdiff
    main: Main.hs
    dependencies: vdiff
    ghc-options: -threaded -O2 -rtsopts

  vdiff-viewer:
    source-dirs: app/vdiff-viewer
    main: Main.hs
    dependencies:
      - vdiff
      - Chart
      - Chart-cairo
    ghc-options: -threaded -O2 -rtsopts

  vdiff-take:
    source-dirs: app/vdiff-take
    main: Main.hs
    dependencies:
      - vdiff
      - random-shuffle
      - extra>=1.6.5
    ghc-options: -threaded -O2 -rtsopts

  

library:
  source-dirs:      src

tests:
  regression:
    main: Regression.hs
    source-dirs: test/regression
    dependencies:
      - rio >= 0.1.0
      - tasty 
      - tasty-hunit
      - tasty-hedgehog
      - tasty-golden
      - hedgehog
      - vdiff
      - file-embed
      - filepath
    ghc-options: -threaded
  integration:
    main: Integration.hs
    source-dirs: test/integration
    dependencies:
      - rio >= 0.1.0
      - tasty 
      - tasty-hunit
      - tasty-hedgehog
      - tasty-golden
      - hedgehog
      - vdiff
      - file-embed
      - filepath
    ghc-options: -threaded


dependencies:
  - base >= 4.7
  - rio >= 0.1.0
  - base16-bytestring
  - bytestring
  - cryptohash
  - file-embed
  - language-c
  - optparse-applicative
  - pretty
  - process >= 1.6.3
  - random
  - safe
  - sqlite-simple
  - direct-sqlite
  - transformers
  - mtl
  - text
  - lens
  - uniplate
  - pptable >= 0.3.0
  - containers
  - unliftio
  - directory
  - template-haskell
  - dlist
  - ilist
  - vector
  - MonadRandom
  - filepath
  - utility-ht
  - beam-core
  - beam-sqlite
  - beam-migrate
  - language-doll
  - time
  
