flags: {}
packages:
- ./vdiff
- ./vdiff-server
- location: ./language-c-extensible
  extra-dep: true

extra-deps:
- pptable-0.3.0.0
- process-1.6.3.0
- rio-0.1.0.0

resolver: lts-11.10

#docker:
#   enable: true
#   image: vdiff/build
#   set-user: false
