# simple bashrc that is placed into the docker image
export PS1='$(pwd) > ' 
export PATH="$HOME/.local/bin:$PATH"

# bash-completion for adiff
source <(adiff --bash-completion-script `which adiff`)
source <(adiff-viewer --bash-completion-script `which adiff-viewer`)
